### ISSUE TITLE
[REJECTED] Inline Block => to simplify blocks with only 1 statament

### ISSUE THREAD

**Issue by igotfr** [vlang/rfcs#11]
Inline Block => to simplify blocks with only 1 statament
useful in multiple nested blocks
```v
// with {}
for nucleotide in dna {
  match nucleotide {
    `A` { rna.write_b(`U`) }
    `T` { rna.write_b(`A`) }
    `C` { rna.write_b(`G`) }
    `G` { rna.write_b(`C`) }
    else { rna.write_b(`?`) }
  }
}

// with =>
for nucleotide in dna =>
  match nucleotide =>
    `A` => rna.write_b(`U`)
    `T` => rna.write_b(`A`)
    `C` => rna.write_b(`G`)
    `G` => rna.write_b(`C`)
    else => rna.write_b(`?`)
```
```v
// with {}
fn f() {
  println('void function')
}

// with =>
fn f() => println('void function')
```
```v
// with {}
if false {
  println('if')
} else if true {
  println('else if')
} else {
  println('else')
}

// with =>
if false => println('if')
else if true => println('else if')
else => println('else')
```

**Comment by bakul** [comment]
Better would be if `match` can be an expression, just like `if`! Then you can do:

```V
for nucleotide in dna {
 rna.write_b(match nucleotide {`A`{`U`}`T`{`A`}`C`{`G`}`G`{`C`}else{`?`}})
}
```

[Edit] Never mind! This already works.

**Comment by igotfr** [comment]
> Better would be if `match` can be an expression, just like `if`! Then you can do:
> 
> ```v
> for nucleotide in dna {
>  rna.write_b(match nucleotide {`A`{`U`}`T`{`A`}`C`{`G`}`G`{`C`}else{`?`}})
> }
> ```
> 
> [Edit] Never mind! This already works.

the one above was only used for illustration

this RFC was rejected and just remains for discussion, comparisons with languages that have this feature and maybe, better proposals
