### ISSUE TITLE
[REJECTED] [test] attribute replacing fn test_f()

### ISSUE THREAD

**Issue by igotfr** [vlang/rfcs#13]
```v
[test]
fn f() {
  assert 2 == 2
}

// instead
fn test_f() {
  assert 2 == 2
}
```

**Comment by igotfr** [comment]
related:
https://github.com/vlang/v/discussions/11924

**Comment by elimisteve** [comment]
Having 2 functions with the same name seems worse than what we have now, doesn't it?

**Comment by igotfr** [comment]
> Having 2 functions with the same name seems worse than what we have now, doesn't it?

it's easier to find quickly in the middle of the code and to differentiate too

**Comment by spytheman** [comment]
The test_ prefix for test functions is preferable - it is easier and simpler to find such functions for both humans and for the test framework too.
